zk cqlin
uiuc-kang-lab/zk-torch pull request #11
Opened 2024-02-22 21:03 UTC by liliatangxy

**Changes**
Add zero knowledge via blinding over all proof objects in cqlin with `+rY` in the same way as #3.

All blinding term calculations are done similarly as in zkcq.

2024-02-22 21:09 UTC, ddkang commented on src/basic_block/cqlin.rs
> +    let r: Vec<_> = (0..9).map(|_| Fr::rand(&mut rng2)).collect();
does it matter how the r is computed? as in, can the prover cheat by choosing a bad r?

2024-02-23 02:01 UTC, arifiorino requested changes

2024-02-23 02:01 UTC, arifiorino commented on src/basic_block/cqlin.rs
> +    let temp: Vec<_> = (0..m).into_par_iter().map(|i| srs.0[n * i]).collect();
It's good that this was fixed cause cqlin was broken when `m>n`. We should have caught this, maybe we should make some sample tests in the future.

2024-02-23 02:01 UTC, arifiorino commented on src/basic_block/cqlin.rs
> +    let temp: Vec<_> = (0..m).into_par_iter().map(|i| srs.1[n * i]).collect();
We don't need to do this. All we need to do is add `+ A_x * r[8]` to `C1` and we're good. Here is a patch for this: [C1_fix.patch](https://github.com/uiuc-kang-lab/zkml_proofs/files/14380980/C1_fix.patch)

2024-02-23 02:13 UTC, liliatangxy commented on src/basic_block/cqlin.rs
> +    let temp: Vec<_> = (0..m).into_par_iter().map(|i| srs.1[n * i]).collect();
Oh yeah you are right

2024-02-23 02:31 UTC, arifiorino commented on src/basic_block/cqlin.rs
> +    let r: Vec<_> = (0..9).map(|_| Fr::rand(&mut rng2)).collect();
I think the prover can theoretically cheat since `Y=X^(2^28-1)`. We should set `Y` randomly in the future. One potential idea is using the challenge_84 file for `Y` and the challenge_85 file for `X`.

2024-02-23 04:17 UTC, ddkang commented on src/basic_block/cqlin.rs
> +    let temp: Vec<_> = (0..m).into_par_iter().map(|i| srs.1[n * i]).collect();
did you push the fix?

2024-02-23 04:18 UTC, ddkang commented on src/basic_block/cqlin.rs
> +    let r: Vec<_> = (0..9).map(|_| Fr::rand(&mut rng2)).collect();
can we fix this now?

2024-02-23 04:42 UTC, liliatangxy commented on src/basic_block/cqlin.rs
> +    let r: Vec<_> = (0..9).map(|_| Fr::rand(&mut rng2)).collect();
I'm not sure if Y is an issue since the verifier also knows Y. The `gamma` opening argument in round 2 should be generated by Fiat-Shamir.

2024-02-23 04:50 UTC, liliatangxy commented on src/basic_block/cqlin.rs
> +    let temp: Vec<_> = (0..m).into_par_iter().map(|i| srs.1[n * i]).collect();
fixed now

2024-02-23 04:54 UTC, arifiorino commented on src/basic_block/cqlin.rs
> +    let r: Vec<_> = (0..9).map(|_| Fr::rand(&mut rng2)).collect();
The issue is if the prover could somehow obfuscate their commitments using the fact that `Y=X^(2^28-1)`. This should be an easy fix, and I was going to include it in my next PR. It might be easier to merge this PR first though.

2024-02-23 04:54 UTC, arifiorino commented on src/basic_block/cqlin.rs
> +    let r: Vec<_> = (0..9).map(|_| Fr::rand(&mut rng2)).collect();
And yeah the `rng` in the prove function is going to be replaced by a fiat-shamir hash function.

2024-02-23 04:56 UTC, arifiorino approved these changes

2024-02-23 05:04 UTC, merged