Fixed matmul
uiuc-kang-lab/zk-torch pull request #16
Opened 2024-03-28 06:12 UTC by liliatangxy

Added matmul with a fixed matrix. The only change necessary to cqlin is RLC for the input and output row commitments. Like the RLC in Aurora, it adds msms to the verifier.

cc single thread
log n | 1xn times nxn proof time (ms)
-- | --
3 | 7.14458
4 | 8.592204
5 | 11.358949
6 | 16.28443
7 | 22.655176
8 | 36.297327
9 | 60.246403
10 | 98.277973

Also moves `calc_pow` into utils

2024-03-28 14:23 UTC, ddkang commented on src/basic_block/matmul_fixed.rs
> +fn calc_pow(alpha: Fr, n: usize) -> Vec<Fr> {
How does the verifier know this was computed correctly, or is this done by both?

2024-03-28 14:34 UTC, liliatangxy commented on src/basic_block/matmul_fixed.rs
> +fn calc_pow(alpha: Fr, n: usize) -> Vec<Fr> {
The verifier obtains the shared rng object and should get the same alpha as the prover, and then computes the powers of alpha.

2024-04-02 02:49 UTC, Vimalakirti approved these changes

2024-04-10 20:53 UTC, arifiorino commented
We need to rebase this over the llama changes.

2024-04-10 20:54 UTC, arifiorino requested changes

2024-04-10 20:54 UTC, arifiorino commented on src/basic_block.rs
> +pub use matmul_fixed::MatMulFixedBasicBlock;
I think we should keep the name of this as `CQLinBasicBlock` because that's what this basic block is based off of. It's cqlin with the combination idea from Aurora.

2024-04-10 21:22 UTC, liliatangxy commented
Finished the merge to master and rename, please review

2024-04-10 21:27 UTC, ddkang commented on src/basic_block/cqlin.rs
> +fn calc_pow(alpha: Fr, n: usize) -> Vec<Fr> {
Is this reused elsewhere?

2024-04-10 21:29 UTC, liliatangxy commented on src/basic_block/cqlin.rs
> +fn calc_pow(alpha: Fr, n: usize) -> Vec<Fr> {
Yeah, it is currently used in multiple files. Should I move it to utils in this pr?

2024-04-10 21:31 UTC, ddkang commented on src/basic_block/cqlin.rs
> +fn calc_pow(alpha: Fr, n: usize) -> Vec<Fr> {
I think this PR is small enough that it's okay to do that now

2024-04-10 21:39 UTC, arifiorino commented
This looks good, except that `cargo run` fails now because it tries to pass a 1d vector times a 2d vector into cqlin. So this error needs to be fixed before this can be merged.

2024-04-10 21:58 UTC, Vimalakirti approved these changes
Except for Ari's request, I have no other concerns.

2024-04-10 22:10 UTC, arifiorino commented
This is the patch you need to apply to fix this:
[fix.patch](https://github.com/uiuc-kang-lab/zkml_proofs/files/14938291/fix.patch)

2024-04-10 22:15 UTC, liliatangxy commented
Added the patch

2024-04-10 22:19 UTC, arifiorino commented
Ok, you also moved `calc_pow` to the `util.rs` file. The issue is that `calc_pow` starts at `alpha^1` in `AlternatingBasicBlock` for a specific security reason. As it is now, the prover can swap the first two elements in `AlternatingBasicBlock`. In order to fix this, you need to change `calc_pow` to start at `alpha^1` in `util.rs`.

2024-04-10 22:32 UTC, liliatangxy commented
Makes sense, fixed

2024-04-10 22:35 UTC, arifiorino approved these changes
Ok, this looks good to me

2024-04-10 22:37 UTC, merged