Layer with reusable weights and tables
uiuc-kang-lab/zk-torch pull request #31
Opened 2024-04-29 03:51 UTC by liliatangxy

Enables reuse of weights and table on top of the layer PR #27 and avoids recomputation for their setups. This also simplifies the handling of weights and tables for the user into providing a weights `HashMap` and configuration of tables by layer. 

Changes:
- Weights are stored in a `HashMap`, and are identified with a user-provided key provided to the `LayerConfig`
- `Graph` has a constructor that handles table creation based on a list of `LayerConfigs`
- Added `Setup` object and moved setup logic. Setups and weights/table `Data` objects are constructed once for each unique hash map entry
- Added `BasicBlockType`, `LayerType`, and for basic blocks `block_type()`, `weights_name()`
- Removed `setup` from `layer` and lower, changed signatures for `run`, etc., to not use `model` when possible

2024-04-29 03:52 UTC, ddkang commented
Raise issues for the last 3 notes

2024-04-29 03:56 UTC, ddkang commented on src/basic_block.rs
> +    "".to_string()
Why don't we just error here?

2024-04-29 03:56 UTC, ddkang commented on src/graph.rs
> +        (BasicBlockType::ChangeSF, BasicBlockType::CQ2)
What's going on here?

2024-04-29 03:56 UTC, ddkang commented on src/graph.rs
> +  pub fn run(&self, inputs: &Vec<&ArrayD<Fr>>) -> Vec<Vec<Vec<ArrayD<Fr>>>> {
What's going on with the vec vec vec stuff?

2024-04-29 03:56 UTC, ddkang commented on src/setup.rs
> +use crate::util::{self, convert_to_data};
Why is this a generic setup file?

2024-04-29 03:57 UTC, ddkang commented
Can we make a GitHub action to run tests when commits are pushed? Can raise an issue

2024-04-29 21:40 UTC, Vimalakirti approved these changes
Thanks! Except for readability, GitHub testing, and CustomLayer (we can delete it if unnecessary) issues, I have no other concerns. 
Btw, shall I close my previous PR since this PR is directly based on that one?

2024-04-29 21:40 UTC, Vimalakirti commented on src/graph.rs
> +        (BasicBlockType::ChangeSF, BasicBlockType::CQ2)
We need to initialize a CQ2 table for every nonlinear basicblock. With this realization, it's great that we no longer mix model weights and lookup tables together. But we could refactor codes (e.g., pack nonlinear basikblocktypes somewhere else) or add comments to make it more clear.

2024-04-30 02:37 UTC, liliatangxy commented on src/graph.rs
> +  pub fn run(&self, inputs: &Vec<&ArrayD<Fr>>) -> Vec<Vec<Vec<ArrayD<Fr>>>> {
The indices are [layer no.][node id in that layer][the output index of that node].

@Vimalakirti Is there a reason why we need the output index?

2024-04-30 16:54 UTC, Vimalakirti commented on src/graph.rs
> +  pub fn run(&self, inputs: &Vec<&ArrayD<Fr>>) -> Vec<Vec<Vec<ArrayD<Fr>>>> {
@liliatangxy we need that because some nodes may return two outputs (e.g., Split). But currently I think we don't have this kind of basicblock.

2024-04-30 16:56 UTC, liliatangxy commented
Cleaned up the graph constructor, added error checking for weights name and CQ2 following a nonlinearity, and moved setup back.
`name()` is actually used for the `Hash` trait, which is needed in the codebase so we don't need to remove it.

I think supporting `CustomLayer` would require us to put `Layer` inside the `LayerConfig`.

2024-04-30 16:59 UTC, liliatangxy commented on src/graph.rs
> +  pub fn run(&self, inputs: &Vec<&ArrayD<Fr>>) -> Vec<Vec<Vec<ArrayD<Fr>>>> {
Ok, I think we can keep that in the code. I can add a comment to clarify this

2024-04-30 17:10 UTC, liliatangxy commented on src/graph.rs
> +        (BasicBlockType::ChangeSF, BasicBlockType::CQ2)
I simplified the logic here by checking whether a BB is a nonlinearity and erroring if it is not followed by CQ2. Right now table generation only uses CQ2 (combining range check with the nonlinearity), can introduce CQ logic in another PR.

2024-05-01 01:37 UTC, Vimalakirti commented
Hi, I found two bugs in `softmax` and `graph`:
- basicblock should not duplicate in graph initialization
- the output node of softmax is incorrect

I've pushed my patch for them, please check.

2024-05-01 18:39 UTC, liliatangxy commented
Thanks for catching them, the changes look good

2024-05-03 22:38 UTC, arifiorino requested changes
I left several detailed comments about this PR. In addition to these, this PR is not able to load an onnx file at all. There are several subtleties in loading an onnx file, and none of these are addressed here.

2024-05-03 22:38 UTC, arifiorino commented on src/basic_block/cq2.rs
> +    format!("CQ2({})", self.name)
This is unnecessary because the `Debug` trait already includes `CQ2` and `self.name`.

2024-05-03 22:38 UTC, arifiorino commented on src/basic_block.rs
> +    BasicBlockType::Constant
Why would the default be `Constant`? I think there should be no default and every basic block should define this. But there is probably a more efficient way of doing this as well (maybe using `format!()` so we don't have to add code to every basic block.

2024-05-03 22:38 UTC, arifiorino commented on src/basic_block.rs
> +  fn name(&self) -> String {
We should think about if we even need this method, because it might be better to just use `format!()` instead everywhere this method is used.

2024-05-03 22:38 UTC, arifiorino commented on src/basic_block.rs
> +  fn weights_name(&self) -> Result<String, String> {
I thought the weights would be part of the `name` itself.

2024-05-03 22:38 UTC, arifiorino commented on src/basic_block.rs
> +impl std::cmp::PartialEq for dyn BasicBlock {
This could also be done by adding `#[derive(Debug, PartialEq)]` to the basic blocks which might be more intuitive.

2024-05-03 22:38 UTC, arifiorino commented on src/graph.rs
>  impl Graph {
Shouldn't we just convert the layers into a `Graph`, and leave the `Graph` struct unchanged?

2024-05-03 22:38 UTC, arifiorino commented on src/layer.rs
> +pub trait Layer {
So we have `run/prove/verify` defined for `BasicBlock`,`Layer`, and `Graph`? we don't need it defined for all these three.

2024-05-03 22:38 UTC, arifiorino commented on src/layer/add.rs
> +use super::{Layer, LayerConfig};
This is too many lines (20) that we will have to write for every layer (there are 154 layers in the tract library)

2024-05-03 22:38 UTC, arifiorino commented on src/graph.rs
> +pub enum SetupType {
This seems a bit hardcoded to me. There might be a more flexible/simpler way to do this.

2024-05-03 22:38 UTC, arifiorino commented on src/basic_block/cq.rs
> +  fn name(&self) -> String {
This is unnecessary because the `Debug` trait already includes `CQ` and `self.name`.

2024-05-03 22:38 UTC, arifiorino commented on src/basic_block/cqlin.rs
> +    let L_V_i_x = L_V_i_x.iter().map(|x| (*x).into()).collect();
Earlier, the setup functions returned `(Vec<G1Projective>,Vec<G2Projective>)` so we didn't have to write conversions like this into the setup functions.

2024-05-03 22:38 UTC, arifiorino commented on src/basic_block/cq2.rs
> +    let L_i_0_x_1 = L_i_0_x_1.iter().map(|x| (*x).into()).collect();
Earlier, the setup functions returned `(Vec<G1Projective>,Vec<G2Projective>)` so we didn't have to write conversions like this into the setup functions.

2024-05-03 22:38 UTC, arifiorino commented on src/basic_block/cq.rs
> +    let L_i_0_x_1 = L_i_0_x_1.iter().map(|x| (*x).into()).collect();
Earlier, the setup functions returned `(Vec<G1Projective>,Vec<G2Projective>)` so we didn't have to write conversions like this into the setup functions.

2024-05-03 22:38 UTC, arifiorino commented on src/basic_block.rs
> +  fn run(&self, _weights: &ArrayD<Fr>, _inputs: &Vec<&ArrayD<Fr>>) -> Vec<ArrayD<Fr>> {
Why change this to `weights`? It could either be the weights, or it could be tables.

2024-05-03 22:38 UTC, arifiorino commented on src/basic_block.rs
> +  fn setup(&self, _srs: &SRS, _model: &ArrayD<Fr>) -> SetupType {
I thought we weren't using `model` anymore.

2024-05-03 22:38 UTC, arifiorino commented on src/basic_block.rs
> +impl std::hash::Hash for dyn BasicBlock {
We could just define a `HashMap` with strings as keys instead, and run the `Debug` trait to generate the keys.

2024-05-04 01:27 UTC, liliatangxy commented on src/basic_block.rs
> +  fn run(&self, _weights: &ArrayD<Fr>, _inputs: &Vec<&ArrayD<Fr>>) -> Vec<ArrayD<Fr>> {
For a basic block without weights, it will be an empty array

2024-05-04 01:30 UTC, liliatangxy commented on src/basic_block/cq2.rs
> +    format!("CQ2({})", self.name)
`format` isn't sufficient for the basic blocks containing `HashTable` e.g., `CQ2`

2024-05-04 01:34 UTC, arifiorino commented on src/basic_block/cq2.rs
> +    format!("CQ2({})", self.name)
The `table_dict` parameter in `CQ2BasicBlock` doesn't contain anything when we're setting it up. It only gets populated during proof time. Therefore it shouldn't be an issue.

2024-05-27 18:52 UTC, closed without merging