Add concat, squeeze, and unsqueeze layers
uiuc-kang-lab/zk-torch pull request #42
Opened 2024-05-28 21:50 UTC by Vimalakirti

(as title states)
The Unsqueeze can only support input data from other nodes instead of itself. This will be fixed later.

2024-05-29 05:36 UTC, liliatangxy approved these changes

2024-05-29 05:36 UTC, liliatangxy commented on src/basic_block/concat.rs
> +}
please avoid removing newlines at the end of files

2024-05-29 15:05 UTC, arifiorino requested changes
I reviewed the files manually and found some mistakes. But I haven't run these layers myself to test, have you run the layers yourself?

2024-05-29 15:05 UTC, arifiorino commented on src/basic_block/concat.rs
> +impl BasicBlock for ConcatBasicBlock {
The logic here is wrong. This should only be defined for 1d vectors because otherwise this can be done with `ReshapeBasicBlock`. And for 1d vectors, this can be done in a manner similar to `PermuteBasicBlock`.

2024-05-29 15:05 UTC, arifiorino commented on src/layer/squeeze.rs
> +      let (mut a, mut b) = (endShape[n - 2], endShape[n - 1]);
`b` always equals 1

2024-05-29 15:05 UTC, arifiorino commented on src/layer/squeeze.rs
> +      let permutation = ((0..a).map(|x| x * b).collect(), (0..b).collect());
This can be rewritten given that `b` always equals 1

2024-05-29 15:05 UTC, arifiorino commented on src/layer/squeeze.rs
> +impl Layer for UnsqueezeLayer {
I just wanted to make clear that we're on the same page about the logic here, and maybe a comment would be useful. This layer adds an axis of length 1. If the axis is anything but the last axis, this can be done trivially using reshape. Otherwise, say we have a shape of `(a,b,c,d)`. Then we first want to insert an axis of length 1 here: `(a,b,c,1,d)`. Then we do a `PermuteBasicBlock` to get `(a,b,c,d,1)`.

2024-05-29 15:05 UTC, arifiorino commented on src/layer/squeeze.rs
> +      let (mut a, mut b) = (startShape[n - 2], startShape[n - 1]);
`b` always equals 1

2024-05-29 15:05 UTC, arifiorino commented on src/layer/squeeze.rs
> +    let axis: isize = attributes.iter().filter(|x| x.name == "axes").next().unwrap().ints[0] as isize;
Sometimes there are multiple axes which are supposed to be squeezed. Or sometimes there are no axes, and it is assumed that all axes of length 1 are to be removed.

2024-05-29 15:05 UTC, arifiorino commented on src/layer/squeeze.rs
> +      let permutation = (vec![0], (0..a * b).collect());
This can be rewritten given that `b` always equals 1

2024-05-29 15:05 UTC, arifiorino commented on src/layer/concat.rs
> +impl Layer for ConcatLayer {
This should run `ReshapeBasicBlock` if the axis is anything except the last axis. Otherwise it should run `ConcatBasicBlock` (wrapped by a `RepeaterBasicBlock`) which is assumed to only run on 1d vectors.

2024-05-29 15:09 UTC, Vimalakirti commented
> I reviewed the files manually and found some mistakes. But I haven't run these layers myself to test, have you run the layers yourself?

yeah, I've manually created one onnx file with Squeeze, Unsqueeze, and Concat. This PR successfully proves the file.

2024-05-29 15:12 UTC, Vimalakirti commented on src/basic_block/concat.rs
> +impl BasicBlock for ConcatBasicBlock {
Why should it be defined for 1d vectors? I think the logic here works well for any concatenation except for the last dimension.

2024-05-29 15:12 UTC, Vimalakirti commented on src/layer/squeeze.rs
> +      let (mut a, mut b) = (endShape[n - 2], endShape[n - 1]);
thanks, I will simplify this part

2024-05-29 15:19 UTC, Vimalakirti commented on src/layer/squeeze.rs
> +    let axis: isize = attributes.iter().filter(|x| x.name == "axes").next().unwrap().ints[0] as isize;
Thanks, let me fix it.

2024-05-29 15:25 UTC, Vimalakirti commented on src/layer/concat.rs
> +impl Layer for ConcatLayer {
I think the problem here is that `ReshapeBasicBlock` can only accept one input instead of `N` inputs for `Concat`. Thus, `ConcatBasicBlock` seems to be fine for me. Maybe creating one `ConcatLastDimBasicBlock` similar to `PermuteBasicBlock` can address your concern (?).

2024-05-29 15:25 UTC, Vimalakirti commented on src/basic_block/concat.rs
> +}
Thanks, let me fix it.

2024-05-29 15:27 UTC, Vimalakirti commented on src/basic_block/concat.rs
> +impl BasicBlock for ConcatBasicBlock {
(There's a similar question below. I put a possible solution there.)

2024-05-29 15:30 UTC, arifiorino commented on src/layer/concat.rs
> +impl Layer for ConcatLayer {
Yes, this is true. Yes, that could work

2024-05-29 15:31 UTC, arifiorino commented on src/basic_block/concat.rs
> +impl BasicBlock for ConcatBasicBlock {
Yes, you are right. But also this file does a bunch of stuff with `Axis(0)` which is irrelevant. The only axis that is significant is the last axis, not the first one.

2024-06-09 22:42 UTC, arifiorino commented on .gitignore
> +*.onnx
I think we still want `sample.onnx` for testing purposes to still be in the repo.

2024-06-10 00:08 UTC, arifiorino commented on src/basic_block/concat.rs
> +// only support concat over dim 0 for now
We could maybe support all axes except for the last axis.

2024-06-10 00:08 UTC, arifiorino commented on src/basic_block/concat.rs
> +      r = ndarray::concatenate(Axis(self.axis), &[r.view(), input.view()]).unwrap();
We can combine all these calls into one call to `ndarray::concatenate`

2024-06-10 00:08 UTC, arifiorino commented on src/basic_block/concat.rs
> +        r = ndarray::concatenate(Axis(self.axis), &[r.view(), input.view()]).unwrap();
We can combine all these calls into one call to `ndarray::concatenate`

2024-06-10 00:08 UTC, arifiorino commented on src/basic_block/concat.rs
> +      inputs[i].iter().zip(outputs[0].index_axis(Axis(self.axis), i).iter()).for_each(|(input, output)| {
The logic here is wrong, I don't think we should use `index_axis`. Here is a photo of how concatenate works which doesn't match this logic:
<img width="492" alt="Screenshot 2024-06-09 at 7 06 31 PM" src="https://github.com/uiuc-kang-lab/zk-torch/assets/5199255/766e4bc4-a90c-485e-a8ea-91b51ec3360b">

2024-06-10 02:34 UTC, arifiorino commented on src/basic_block/concat.rs
> +      assert!(inputs[0].shape()[1..] == input.shape()[1..]);
This assert is not right. Also we should assert that the axis is not the last axis.

2024-06-10 02:34 UTC, arifiorino commented on src/basic_block/copy_constraint.rs
> +fn construct_ssig(
It seems that this PR is building off of #43. Therefore we should wait to push that PR before we push this one.

2024-06-10 02:34 UTC, arifiorino commented on src/layer/concat.rs
> +fn get_concat_indices(input_shapes: &Vec<&Vec<usize>>, output_shape: &Vec<usize>, axis: usize) -> Vec<ArrayD<Option<IxDyn>>> {
Can you add a comment explaining what this function does?

2024-06-10 02:34 UTC, arifiorino commented on src/layer/concat.rs
> +        let add_output = graph.addNode(add, vec![cc_outputs.pop().unwrap(), cc_outputs.pop().unwrap()]);
This seems inefficient and it is also unsafe since `copy_constraint` is unsafe.

2024-06-10 03:08 UTC, Vimalakirti commented on src/basic_block/copy_constraint.rs
> +fn construct_ssig(
yeah, let's wait for it.

2024-06-10 03:09 UTC, Vimalakirti commented on src/layer/concat.rs
> +        let add_output = graph.addNode(add, vec![cc_outputs.pop().unwrap(), cc_outputs.pop().unwrap()]);
I think this cannot be more efficient as AddBasicBlock only accepts two inputs currently.
And `copy_constraint` will be safe soon after proper blinding.

2024-06-10 04:56 UTC, arifiorino commented on src/layer/concat.rs
> +        let add_output = graph.addNode(add, vec![cc_outputs.pop().unwrap(), cc_outputs.pop().unwrap()]);
No, this is not how this works. Don't resolve a conversation without actually resolving it.

2024-06-10 05:40 UTC, Vimalakirti commented on src/layer/concat.rs
> +        let add_output = graph.addNode(add, vec![cc_outputs.pop().unwrap(), cc_outputs.pop().unwrap()]);
Sorry, I thought my comment had answered your concerns. What's your suggestion then?

2024-07-08 03:13 UTC, liliatangxy commented on src/layer/concat.rs
> +        let add_output = graph.addNode(add, vec![cc_outputs.pop().unwrap(), cc_outputs.pop().unwrap()]);
Is it possible to combine each input to concat into a single `ArrayD` input? Then we would only need to use one `CopyConstraintBasicBlock` and no additions

2024-07-08 18:19 UTC, Vimalakirti commented on src/layer/concat.rs
> +        let add_output = graph.addNode(add, vec![cc_outputs.pop().unwrap(), cc_outputs.pop().unwrap()]);
I think it's not possible because the above case is for concatenation through the last dimension. We cannot generate a corresponding single ArrayD<Data> for proving in the case.
For instance, imaging 4 input arrays are in shape [16,2], then their commitment will all be in shape [16,1]. The output array would be in shape [16,8], of which commitment shape would be [16,1]. If we combine each input into single input of size [16,8] first for copy constraint, we do not know how to combine their commitments (4 [16,1] arrays) into 1 [16,1] Data array for copy constraint proving and verification.

2024-07-08 20:29 UTC, ddkang commented on src/layer/concat.rs
> +  fn graph(input_shapes: &Vec<&Vec<usize>>, _constants: &Vec<Option<&ArrayD<Fr>>>, attributes: &Vec<&AttributeProto>) -> (Graph, Vec<Vec<usize>>) {
Please leave comments describing the high level algorithm

2024-07-08 20:31 UTC, ddkang commented on src/layer/squeeze.rs
> +  fn graph(input_shapes: &Vec<&Vec<usize>>, _constants: &Vec<Option<&ArrayD<Fr>>>, attributes: &Vec<&AttributeProto>) -> (Graph, Vec<Vec<usize>>) {
Ditto on comments

2024-07-09 16:02 UTC, ddkang commented on src/layer/concat.rs
> +        let add_output = graph.addNode(add, vec![cc_outputs.pop().unwrap(), cc_outputs.pop().unwrap()]);
Is this comment resolved?

2024-07-09 18:16 UTC, Vimalakirti commented on src/layer/concat.rs
> +        let add_output = graph.addNode(add, vec![cc_outputs.pop().unwrap(), cc_outputs.pop().unwrap()]);
@liliatangxy @arifiorino

2024-07-10 16:14 UTC, liliatangxy commented on src/layer/concat.rs
> +        let add_output = graph.addNode(add, vec![cc_outputs.pop().unwrap(), cc_outputs.pop().unwrap()]);
lgtm

2024-07-10 18:54 UTC, ddkang approved these changes

2024-07-10 18:55 UTC, merged