Conv layer
uiuc-kang-lab/zk-torch pull request #43
Opened 2024-05-29 23:36 UTC by liliatangxy

Added Conv layer. For now the layer proves weights splatting and uses MatMul instead of CQLin since fixing this would require changes to onnx processing.

2024-05-30 05:28 UTC, ddkang commented
Isn't the verifier check required for soundness?

2024-05-30 05:29 UTC, ddkang commented on src/layer/conv.rs
> +use crate::basic_block::*;
Unless this is a fully general ND conv, call it conv_<whatever>d

2024-05-30 05:31 UTC, ddkang commented on src/layer/conv.rs
> +use crate::graph::*;
This file is very complicated. Are there ways to simplify?

2024-05-30 05:31 UTC, liliatangxy commented on src/layer/conv.rs
> +use crate::basic_block::*;
It is general

2024-05-30 13:17 UTC, Vimalakirti approved these changes

2024-05-30 13:17 UTC, Vimalakirti commented on src/layer/conv.rs
> +    let output_dim = permutation_padded.dim();
To prevent possible bugs, maybe we can remove `output_dim` from `CopyConstraintBasicBlock` as it is exactly the same as `permutation.dim()`

2024-05-30 13:17 UTC, Vimalakirti commented on src/main.rs
> +  let srs = &ptau::load_file("challenge14", 14, 14);
This file is missing.

2024-05-30 13:17 UTC, Vimalakirti commented on src/layer/conv.rs
> +    let strides: Vec<_> = attributes.iter().filter(|x| x.name == "strides").next().unwrap().ints.iter().map(|x| *x as usize).collect();
"strides" may not exist sometimes (the default value is 1)

2024-06-10 00:16 UTC, arifiorino requested changes

2024-06-10 00:16 UTC, arifiorino commented on src/basic_block/copy_constraint.rs
> +    return (proof, vec![setup.1[0].into(), setup.1[1].into()], evals);
This reveals the inputs to the verifier. Specifically, `fj_poly` are the polynomials of the inputs. And `q1_evals` includes those polynomials evaluated at a random challenge `a`. And then `q1_evals` is sent to the verifier since it is added to `evals`. Through a polynomial interpolation attack, the inputs can be recovered by the verifier.

2024-07-08 00:00 UTC, Vimalakirti commented on src/layer/conv.rs
> +pub fn pad<G: Clone>(input: &ArrayD<G>, padding: &Vec<[usize; 2]>, pad_val: &G) -> ArrayD<G> {
we have another `pub fn pad` in `util`. Maybe it would be clearer to add comments or change its name.

2024-07-08 00:00 UTC, Vimalakirti commented on src/layer/conv.rs
> +
Do we need to consider dilations?
(reference: https://onnx.ai/onnx/operators/onnx__Conv.html)

2024-07-08 03:37 UTC, liliatangxy commented on src/layer/conv.rs
> +
I don't think any of the CNNs we are proving have non-default values for dilations. I can make a not implemented error for it

2024-07-08 16:19 UTC, liliatangxy commented on src/layer/conv.rs
> +pub fn pad<G: Clone>(input: &ArrayD<G>, padding: &Vec<[usize; 2]>, pad_val: &G) -> ArrayD<G> {
renamed the one in util since it is specific to padding to the next pow of 2. we could also move this to util

2024-07-10 23:42 UTC, ddkang commented on src/layer/conv.rs
> +pub fn pad<G: Clone>(input: &ArrayD<G>, padding: &Vec<[usize; 2]>, pad_val: &G) -> ArrayD<G> {
Can these pad functions be merged?

2024-07-10 23:42 UTC, ddkang commented on src/layer/conv.rs
> +use crate::graph::*;
Checking in on this.

2024-07-10 23:49 UTC, liliatangxy commented on src/layer/conv.rs
> +use crate::graph::*;
I think we can move `pad` to `utils`, merge it with the other pad, and get `splat_pad` to use the other pad.

2024-07-11 00:16 UTC, ddkang commented on src/layer/conv.rs
> +use crate::graph::*;
Sounds good

2024-07-11 17:23 UTC, merged